stages:
  - Webapp build
  - Webapp test
cache:
  paths:
    - .yarn
    - node_modules/
Yarn Build:
  image: node:18.4.0
  stage: Webapp build
  needs: []
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn build
  retry: 1
Prettier check:
  image: node:18.4.0
  stage: Webapp test
  needs: [Yarn Build]
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn lint:prettier
  retry: 1
Eslint:
  image: node:18.4.0
  stage: Webapp test
  needs: [Yarn Build]
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn lint
  retry: 1
